### ISSUE TITLE
 PCA(supervised), RandomizedPCA(supervised)

### ISSUE THREAD

**Issue by StevenLOL** [dikien/Machine-Learning-Newspaper#1]
HI, I am thinking, they can put into unsupervised group.

**Comment by dikien** [comment]
Hi, Steven. Thank you for your comment. As you said, I changed from [PCA(supervised), RandomizedPCA(supervised), LDA(unsupervised)] to [PCA(unsupervised), RandomizedPCA(unsupervised), LDA(supervised)]
